<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Security + performance pass:
 *   - device_token          (per-machine hashed IoT credentials)
 *   - refresh_token         (JWT refresh rotation/revocation)
 *   - machine_command_audit (who sent which command, when)
 *   - machine.device_tokens_enabled (kill switch)
 *   - machine_telemetry (machine_id, recorded_at DESC) composite index
 */
final class Version20260930000001 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Device tokens, refresh tokens, command audit, machine device kill switch, telemetry composite index';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE device_token (id UUID NOT NULL, machine_id UUID NOT NULL, token_hash VARCHAR(128) NOT NULL, label VARCHAR(120) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, last_used_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, revoked_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_DEVICE_TOKEN_HASH ON device_token (token_hash)');
        $this->addSql('CREATE INDEX idx_device_token_machine ON device_token (machine_id)');
        $this->addSql('ALTER TABLE device_token ADD CONSTRAINT FK_DEVICE_TOKEN_MACHINE FOREIGN KEY (machine_id) REFERENCES machine (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('COMMENT ON TABLE device_token IS \'Per-machine hashed IoT credentials (telemetry ingest; future MQTT consumer)\'');

        // id is a PostgreSQL IDENTITY column (what Doctrine expects for
        //GeneratedValue(strategy: 'IDENTITY') on this platform), NOT a
        // hand-made sequence with a nextval() default — the latter shows up as
        // a schema diff (DROP DEFAULT / ADD GENERATED ... AS IDENTITY).
        $this->addSql('CREATE TABLE refresh_token (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, refresh_token VARCHAR(128) NOT NULL, username VARCHAR(180) NOT NULL, valid TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_refresh_token ON refresh_token (refresh_token)');
        $this->addSql('CREATE INDEX idx_refresh_token_username ON refresh_token (username)');
        $this->addSql('COMMENT ON TABLE refresh_token IS \'JWT refresh tokens (hashed at rest, rotated on use)\'');

        $this->addSql('CREATE TABLE machine_command_audit (id UUID NOT NULL, machine_id UUID NOT NULL, user_id UUID DEFAULT NULL, command VARCHAR(32) NOT NULL, value DOUBLE PRECISION DEFAULT NULL, transport VARCHAR(32) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX idx_command_audit_machine_created ON machine_command_audit (machine_id, created_at)');
        $this->addSql('CREATE INDEX idx_command_audit_user ON machine_command_audit (user_id)');
        $this->addSql('ALTER TABLE machine_command_audit ADD CONSTRAINT FK_CMD_AUDIT_MACHINE FOREIGN KEY (machine_id) REFERENCES machine (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE machine_command_audit ADD CONSTRAINT FK_CMD_AUDIT_USER FOREIGN KEY (user_id) REFERENCES "user" (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('COMMENT ON TABLE machine_command_audit IS \'Audit of accepted machine commands (acceptance != execution)\'');

        $this->addSql('ALTER TABLE machine ADD device_tokens_enabled BOOLEAN NOT NULL DEFAULT true');
        $this->addSql('COMMENT ON COLUMN machine.device_tokens_enabled IS \'Kill switch: when false, every device token of this machine is refused\'');

        // Composite index matching the hot read pattern (newest-first per machine).
        // Postgres scans a DESC index backwards equally well, but an explicit
        // DESC composite documents intent and keeps ASC keyset walks cheap.
        $this->addSql('DROP INDEX idx_telemetry_machine_recorded');
        $this->addSql('CREATE INDEX idx_telemetry_machine_recorded_desc ON machine_telemetry (machine_id, recorded_at DESC)');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE device_token');
        $this->addSql('DROP TABLE refresh_token');
        $this->addSql('DROP TABLE machine_command_audit');
        $this->addSql('ALTER TABLE machine DROP device_tokens_enabled');
        $this->addSql('CREATE INDEX idx_telemetry_machine_recorded ON machine_telemetry (machine_id, recorded_at)');
        $this->addSql('DROP INDEX idx_telemetry_machine_recorded_desc');
    }
}
